namespace SpriteKind {
    export const Hitbox = SpriteKind.create()
    export const MiniMenu = SpriteKind.create()
    export const Sans = SpriteKind.create()
    export const ActHitbox = SpriteKind.create()
    export const Flowey = SpriteKind.create()
    export const Soul = SpriteKind.create()
    export const BattleSpr = SpriteKind.create()
    export const TextSpawn = SpriteKind.create()
    export const Locator = SpriteKind.create()
    export const FinalProjectile = SpriteKind.create()
}
sprites.onOverlap(SpriteKind.ActHitbox, SpriteKind.Flowey, function (sprite, otherSprite) {
    if (!(dialogueOpen)) {
        timer.after(100, function () {
            if (!(dialogueOpen)) {
                dialogueOpen = true
                game.showLongText("Howdy! I'm FLOWEY. FLOWEY the FLOWER!", DialogLayout.Bottom)
                game.showLongText("Hmmm... You're new to the UNDERGROUND, aren'tcha?", DialogLayout.Bottom)
                game.showLongText(" Golly, you must be so confused.", DialogLayout.Bottom)
                game.showLongText("Someone ought to teach you how things work around here!", DialogLayout.Bottom)
                game.showLongText("I guess little old me will have to do. Ready? Here we go!", DialogLayout.Bottom)
                dialogueOpen = false
                initiateFloweyBattle()
            }
        })
    }
})
scene.onOverlapTile(SpriteKind.Hitbox, assets.tile`myTile24`, function (sprite, location) {
    tileUtil.replaceAllTiles(assets.tile`myTile24`, assets.tile`transparency8`)
    room += 1
    loadNextRoom()
})
sprites.onOverlap(SpriteKind.ActHitbox, SpriteKind.Sans, function (sprite, otherSprite) {
    if (!(dialogueOpen)) {
        timer.after(100, function () {
            if (!(dialogueOpen)) {
                dialogueOpen = true
                game.showLongText("sorry bud, can't let ya through.", DialogLayout.Top)
                game.showLongText("game's not finished.", DialogLayout.Top)
                game.showLongText("come back in a later version.", DialogLayout.Top)
                dialogueOpen = false
            }
        })
    }
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    if (!(dialogueOpen)) {
        timer.after(50, function () {
            friskActHitbox = sprites.create(img`
                2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 
                2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 
                2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 
                2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 
                2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 
                2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 
                2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 
                2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 
                2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 
                2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 
                2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 
                2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 
                2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 
                2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 
                2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 
                2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 
                `, SpriteKind.ActHitbox)
            friskActHitbox.setFlag(SpriteFlag.Invisible, true)
            friskActHitbox.setPosition(friskHitbox.x, friskHitbox.y)
            timer.after(50, function () {
                sprites.destroyAllSpritesOfKind(SpriteKind.ActHitbox)
            })
        })
    }
    story.clearAllText()
})
sprites.onOverlap(SpriteKind.Projectile, SpriteKind.Soul, function (sprite, otherSprite) {
    sprites.destroyAllSpritesOfKind(SpriteKind.Projectile)
    floweyBattleSpr.setImage(img`
        ................................
        ..........fffff..fffff..........
        .........f1ff11ff11ff1f.........
        ........f111ffffffff111f........
        ......ffffff11111111ffffff......
        .....f111ff1ff1111ff1ff111f.....
        ....f11fff11f1f11f1f11fff11f....
        ....f1111f11fff11fff11f1111f....
        ....ff111f1f11111111f1f111ff....
        ......f111f1ff1111ff1f111f......
        .......ffff1f1ffff1f1ffff.......
        ..........f1fff11fff1f..........
        ..........f1f1ffff1f1f..........
        ..........f11ff11ff11f..........
        .......fffff11ffff11fffff.......
        .......f11fff111111fff11f.......
        .......f1111ffffffff1111f.......
        .......f1f1111ffff1111f1f.......
        .......ff111fff11fff111ff.......
        .........fff..f11f..fff.........
        .............f111f..............
        .............f11f...............
        .............f11f...............
        .............f111f..............
        ..............f11f..............
        .............ff111ff............
        ............f1f111f1f...........
        ............f11fff11f...........
        .............f11111f............
        ..............fffff.............
        ................................
        ................................
        `)
    statusbar.value += -19
    scene.cameraShake(4, 500)
    timer.after(1000, function () {
        game.showLongText(" You idiot!", DialogLayout.Bottom)
        game.showLongText("In this world, it's kill or BE killed.", DialogLayout.Bottom)
        game.showLongText("Why would ANYONE pass up an opportunity like this!?", DialogLayout.Bottom)
        projectile = sprites.createProjectileFromSprite(img`
            . 1 1 . 
            1 1 1 1 
            1 1 1 1 
            . 1 1 . 
            `, floweyNPC, 0, 0)
        projectile.x += -32
        projectile.y += -32
        projectile2 = sprites.createProjectileFromSprite(img`
            . 1 1 . 
            1 1 1 1 
            1 1 1 1 
            . 1 1 . 
            `, floweyNPC, 0, 0)
        projectile2.x += 32
        projectile2.y += -32
        for (let value5 of sprites.allOfKind(SpriteKind.Projectile)) {
            value5.setKind(SpriteKind.FinalProjectile)
            value5.setFlag(SpriteFlag.DestroyOnWall, false)
            value5.setFlag(SpriteFlag.GhostThroughWalls, true)
        }
        timer.after(500, function () {
            game.showLongText("DIE.", DialogLayout.Bottom)
            animation.runImageAnimation(
            floweyBattleSpr,
            [img`
                ..........fffff..fffff..........
                .........f1ff11ff11ff1f.........
                ........f111ffffffff111f........
                ......ffffff11111111ffffff......
                .....f111ff1ff1111ff1ff111f.....
                ....f11fff11f1f11f1f11fff11f....
                ....f1111f11fff11fff11f1111f....
                ....ff111f1f11111111f1f111ff....
                ......f111f1ffffffff1f111f......
                .......ffff1f1f11f1f1ffff.......
                ..........f1ffffffff1f..........
                ..........f1ffffffff1f..........
                ..........f1f1f11f1f1f..........
                .......fffff1ffffff1fffff.......
                .......f11fff111111fff11f.......
                .......f1111ffffffff1111f.......
                .......f1f1111ffff1111f1f.......
                .......ff111fff11fff111ff.......
                .........fff..f11f..fff.........
                .............f111f..............
                .............f111f..............
                .............f11f...............
                .............f11f...............
                .............f111f..............
                ..............f11f..............
                .............ff111ff............
                ............f1f111f1f...........
                ............f11fff11f...........
                .............f11111f............
                ..............fffff.............
                ................................
                ................................
                `,img`
                ................................
                ..........fffff..fffff..........
                .........f1ff11ff11ff1f.........
                ........f111ffffffff111f........
                ......ffffff11111111ffffff......
                .....f111ff1ff1111ff1ff111f.....
                ....f11fff11f1f11f1f11fff11f....
                ....f1111f11fff11fff11f1111f....
                ....ff111f1f11111111f1f111ff....
                ......f111f1ff1111ff1f111f......
                .......ffff1f1ffff1f1ffff.......
                ..........f1fff11fff1f..........
                ..........f1f1ffff1f1f..........
                ..........f11ff11ff11f..........
                .......fffff11ffff11fffff.......
                .......f11fff111111fff11f.......
                .......f1111ffffffff1111f.......
                .......f1f1111ffff1111f1f.......
                .......ff111fff11fff111ff.......
                .........fff..f11f..fff.........
                .............f111f..............
                .............f11f...............
                .............f11f...............
                .............f111f..............
                ..............f11f..............
                .............ff111ff............
                ............f1f111f1f...........
                ............f11fff11f...........
                .............f11111f............
                ..............fffff.............
                ................................
                ................................
                `],
            100,
            true
            )
            projectile.follow(friskSoul, 10)
            projectile2.follow(friskSoul, 10)
        })
    })
})
scene.onOverlapTile(SpriteKind.ActHitbox, assets.tile`myTile19`, function (sprite, location) {
    if (!(dialogueOpen)) {
        timer.after(100, function () {
            if (!(dialogueOpen)) {
                dialogueOpen = true
                game.showLongText("(Flowers. They seem to have broken your fall.)", DialogLayout.Top)
                dialogueOpen = false
            }
        })
    }
})
function loadNextRoom () {
    color.setPalette(
    color.Black
    )
    color.startFadeFromCurrent(color.originalPalette, 100)
    if (room == 0) {
        tiles.setCurrentTilemap(tileUtil.createSmallMap(tilemap`level1`))
    } else if (room == 1) {
        tiles.setCurrentTilemap(tileUtil.createSmallMap(tilemap`level5`))
    } else if (room == 2) {
        tiles.setCurrentTilemap(tileUtil.createSmallMap(tilemap`level12`))
    }
    for (let value of tiles.getTilesByType(assets.tile`myTile32`)) {
        tiles.placeOnTile(friskHitbox, value)
        tiles.setTileAt(value, assets.tile`transparency8`)
    }
    for (let value2 of tiles.getTilesByType(assets.tile`myTile20`)) {
        sansNPC = sprites.create(img`
            . . . . . . . . . . . . . . . . 
            . . . . . f f f f f f . . . . . 
            . . . . f 1 1 1 1 1 1 f . . . . 
            . . . f 1 f f 1 1 f f 1 f . . . 
            . . . f 1 f f 1 1 f f 1 f . . . 
            . . . . f 1 1 f f 1 1 f . . . . 
            . . . f 1 f f f f f f 1 f . . . 
            . . . f f 1 f 1 1 f 1 f f . . . 
            . . f 6 1 f f f f f f 1 6 f . . 
            . f 6 6 6 f f 1 1 f f 6 6 6 f . 
            . f 6 6 f 6 1 1 1 1 6 f 6 6 f . 
            . . f 6 6 f 1 1 1 1 f 6 6 f . . 
            . . . f 1 6 f f f f 6 1 f . . . 
            . . . f 1 f f f f f f 1 f . . . 
            . . . f f f f . . f f f f . . . 
            . . f 1 1 1 f . . f 1 1 1 f . . 
            `, SpriteKind.Sans)
        tiles.placeOnTile(sansNPC, value2)
        tiles.setTileAt(value2, assets.tile`myTile3`)
    }
    for (let value3 of tiles.getTilesByType(assets.tile`myTile29`)) {
        floweyNPC = sprites.create(img`
            . . . . f f f . . f f f . . . . 
            . . . f 5 5 5 f f 5 5 5 f . . . 
            . . . f 5 f f f f f f 5 f . . . 
            . f f 5 f 1 1 1 1 1 1 f 5 f f . 
            f 5 5 f 1 1 f 1 1 f 1 1 f 5 5 f 
            f 5 5 f 1 f 1 1 1 1 f 1 f 5 5 f 
            . f f 5 f 1 f f f f 1 f 5 f f . 
            . f 5 5 5 f f f f f f 5 5 5 f . 
            . f 5 5 f f 7 7 f . . f 5 5 f . 
            . . f f . f 7 7 f . . . f f . . 
            . . . . . . f 7 7 f . . . . . . 
            . . . . . . . f 7 7 f . . . . . 
            . . . . . . . f 7 7 f . . . . . 
            . . . . . . f 7 7 f . . . . . . 
            . . . . . . f 7 7 f . . . . . . 
            . . . . . . . f f . . . . . . . 
            `, SpriteKind.Flowey)
        tiles.placeOnTile(floweyNPC, value3)
        tiles.setTileAt(value3, assets.tile`myTile18`)
        floweyNPC.x += 4
        floweyNPC.y += -8
    }
}
function initiateFloweyBattle () {
    color.setPalette(
    color.Black
    )
    sprites.destroyAllSpritesOfKind(SpriteKind.Player)
    sprites.destroyAllSpritesOfKind(SpriteKind.Hitbox)
    sprites.destroyAllSpritesOfKind(SpriteKind.Sans)
    sprites.destroyAllSpritesOfKind(SpriteKind.ActHitbox)
    sprites.destroyAllSpritesOfKind(SpriteKind.Flowey)
    tiles.setCurrentTilemap(tileUtil.createSmallMap(tilemap`level8`))
    color.startFadeFromCurrent(color.originalPalette, 500)
    timer.after(500, function () {
        friskSoul = sprites.create(img`
            2 2 . 2 
            2 2 2 2 
            2 2 2 2 
            . 2 2 . 
            `, SpriteKind.Soul)
        floweyBattleSpr = sprites.create(img`
            ................................
            ................................
            ................................
            ................................
            ................................
            ..........fffff..fffff..........
            .........f1ff11ff11ff1f.........
            ........f111ffffffff111f........
            ......ffffff11111111ffffff......
            .....f111ff111f11f111ff111f.....
            ....f11fff1111f11f1111fff11f....
            ....f1111f1111f11f1111f1111f....
            ....ff111f11f111111f11f111ff....
            ......f111f11ffffff11f111f......
            .......fffff1f1111f1fffff.......
            .......f11fff1ffff1fff11f.......
            .......f1111ffffffff1111f.......
            .......f1f1111ffff1111f1f.......
            .......ff111fff11fff111ff.......
            .........fff..f11f..fff.........
            .............f111f..............
            .............f11f...............
            .............f11f...............
            .............f111f..............
            ..............f11f..............
            .............ff111ff............
            ............f1f111f1f...........
            ............f11fff11f...........
            .............f11111f............
            ..............fffff.............
            ................................
            ................................
            `, SpriteKind.BattleSpr)
        statusbar = statusbars.create(20, 4, StatusBarKind.Health)
        statusbar.positionDirection(CollisionDirection.Bottom)
        statusbar.setLabel("HP")
        statusbar.max = 20
        controller.moveSprite(friskSoul, 40, 40)
        for (let value4 of tiles.getTilesByType(assets.tile`myTile34`)) {
            tiles.placeOnTile(floweyBattleSpr, value4)
            tiles.setTileAt(value4, assets.tile`transparency8`)
            floweyBattleSpr.x += 4
        }
        timer.after(10, function () {
            game.showLongText("See that heart? That is your SOUL, the very culmination of your being!", DialogLayout.Bottom)
            game.showLongText("Your SOUL starts off weak, but can grow strong if you gain a lot of LV. ", DialogLayout.Bottom)
            game.showLongText("What's LV stand for? Why, LOVE, of course!", DialogLayout.Bottom)
            game.showLongText("You want some LOVE, don't you? Don't worry, I'll share some with you!", DialogLayout.Bottom)
            animation.runImageAnimation(
            floweyBattleSpr,
            [img`
                ................................
                ................................
                ...........................1....
                .........................11111..
                ...........................1....
                ..........fffff..fffff..........
                .........f1ff11ff11ff1f.........
                ........f111ffffffff111f........
                ......ffffff11111111ffffff......
                .....f111ff111f111111ff111f.....
                ....f11fff1111f1111111fff11f....
                ....f1111f1111f11ff111f1111f....
                ....ff111f11f111111f11f111ff....
                ......f111f11ffffff11f111f......
                .......fffff1f1f1111fffff.......
                .......f11fff1f1111fff11f.......
                .......f1111ffffffff1111f.......
                .......f1f1111ffff1111f1f.......
                .......ff111fff11fff111ff.......
                .........fff..f11f..fff.........
                .............f111f..............
                .............f11f...............
                .............f11f...............
                .............f111f..............
                ..............f11f..............
                .............ff111ff............
                ............f1f111f1f...........
                ............f11fff11f...........
                .............f11111f............
                ..............fffff.............
                ................................
                ................................
                `,img`
                ...........................1....
                ...........................1....
                ..........................111...
                .........................11111..
                ..........................111...
                ..........fffff..fffff.....1....
                .........f1ff11ff11ff1f....1....
                ........f111ffffffff111f........
                ......ffffff11111111ffffff......
                .....f111ff111f111111ff111f.....
                ....f11fff1111f1111111fff11f....
                ....f1111f1111f11ff111f1111f....
                ....ff111f11f111111f11f111ff....
                ......f111f11ffffff11f111f......
                .......fffff1f1f1111fffff.......
                .......f11fff1f1111fff11f.......
                .......f1111ffffffff1111f.......
                .......f1f1111ffff1111f1f.......
                .......ff111fff11fff111ff.......
                .........fff..f11f..fff.........
                .............f111f..............
                .............f11f...............
                .............f11f...............
                .............f111f..............
                ..............f11f..............
                .............ff111ff............
                ............f1f111f1f...........
                ............f11fff11f...........
                .............f11111f............
                ..............fffff.............
                ................................
                ................................
                `,img`
                ................................
                ................................
                ...........................1....
                ..........................111...
                ...........................1....
                ..........fffff..fffff..........
                .........f1ff11ff11ff1f.........
                ........f111ffffffff111f........
                ......ffffff11111111ffffff......
                .....f111ff111f111111ff111f.....
                ....f11fff1111f1111111fff11f....
                ....f1111f1111f11ff111f1111f....
                ....ff111f11f111111f11f111ff....
                ......f111f11ffffff11f111f......
                .......fffff1f1f1111fffff.......
                .......f11fff1f1111fff11f.......
                .......f1111ffffffff1111f.......
                .......f1f1111ffff1111f1f.......
                .......ff111fff11fff111ff.......
                .........fff..f11f..fff.........
                .............f111f..............
                .............f11f...............
                .............f11f...............
                .............f111f..............
                ..............f11f..............
                .............ff111ff............
                ............f1f111f1f...........
                ............f11fff11f...........
                .............f11111f............
                ..............fffff.............
                ................................
                ................................
                `,img`
                ................................
                ................................
                ...........................1....
                ..........................111...
                ...........................1....
                ..........fffff..fffff..........
                .........f1ff11ff11ff1f.........
                ........f111ffffffff111f........
                ......ffffff11111111ffffff......
                .....f111ff111f111111ff111f.....
                ....f11fff1111f1111111fff11f....
                ....f1111f1111f11ff111f1111f....
                ....ff111f11f111111f11f111ff....
                ......f111f11ffffff11f111f......
                .......fffff1f1f1111fffff.......
                .......f11fff1f1111fff11f.......
                .......f1111ffffffff1111f.......
                .......f1f1111ffff1111f1f.......
                .......ff111fff11fff111ff.......
                .........fff..f11f..fff.........
                .............f111f..............
                .............f11f...............
                .............f11f...............
                .............f111f..............
                ..............f11f..............
                .............ff111ff............
                ............f1f111f1f...........
                ............f11fff11f...........
                .............f11111f............
                ..............fffff.............
                ................................
                ................................
                `,img`
                ................................
                ................................
                ................................
                ...........................1....
                ................................
                ..........fffff..fffff..........
                .........f1ff11ff11ff1f.........
                ........f111ffffffff111f........
                ......ffffff11111111ffffff......
                .....f111ff111f111111ff111f.....
                ....f11fff1111f1111111fff11f....
                ....f1111f1111f11ff111f1111f....
                ....ff111f11f111111f11f111ff....
                ......f111f11ffffff11f111f......
                .......fffff1f1f1111fffff.......
                .......f11fff1f1111fff11f.......
                .......f1111ffffffff1111f.......
                .......f1f1111ffff1111f1f.......
                .......ff111fff11fff111ff.......
                .........fff..f11f..fff.........
                .............f111f..............
                .............f11f...............
                .............f11f...............
                .............f111f..............
                ..............f11f..............
                .............ff111ff............
                ............f1f111f1f...........
                ............f11fff11f...........
                .............f11111f............
                ..............fffff.............
                ................................
                ................................
                `,img`
                ................................
                ................................
                ................................
                ...........................1....
                ................................
                ..........fffff..fffff..........
                .........f1ff11ff11ff1f.........
                ........f111ffffffff111f........
                ......ffffff11111111ffffff......
                .....f111ff111f111111ff111f.....
                ....f11fff1111f1111111fff11f....
                ....f1111f1111f11ff111f1111f....
                ....ff111f11f111111f11f111ff....
                ......f111f11ffffff11f111f......
                .......fffff1f1f1111fffff.......
                .......f11fff1f1111fff11f.......
                .......f1111ffffffff1111f.......
                .......f1f1111ffff1111f1f.......
                .......ff111fff11fff111ff.......
                .........fff..f11f..fff.........
                .............f111f..............
                .............f11f...............
                .............f11f...............
                .............f111f..............
                ..............f11f..............
                .............ff111ff............
                ............f1f111f1f...........
                ............f11fff11f...........
                .............f11111f............
                ..............fffff.............
                ................................
                ................................
                `,img`
                ................................
                ................................
                ................................
                ................................
                ................................
                ..........fffff..fffff..........
                .........f1ff11ff11ff1f.........
                ........f111ffffffff111f........
                ......ffffff11111111ffffff......
                .....f111ff111f111111ff111f.....
                ....f11fff1111f1111111fff11f....
                ....f1111f1111f11ff111f1111f....
                ....ff111f11f111111f11f111ff....
                ......f111f11ffffff11f111f......
                .......fffff1f1f1111fffff.......
                .......f11fff1f1111fff11f.......
                .......f1111ffffffff1111f.......
                .......f1f1111ffff1111f1f.......
                .......ff111fff11fff111ff.......
                .........fff..f11f..fff.........
                .............f111f..............
                .............f11f...............
                .............f11f...............
                .............f111f..............
                ..............f11f..............
                .............ff111ff............
                ............f1f111f1f...........
                ............f11fff11f...........
                .............f11111f............
                ..............fffff.............
                ................................
                ................................
                `,img`
                ................................
                ................................
                ................................
                ................................
                ................................
                ..........fffff..fffff..........
                .........f1ff11ff11ff1f.........
                ........f111ffffffff111f........
                ......ffffff11111111ffffff......
                .....f111ff111f111111ff111f.....
                ....f11fff1111f1111111fff11f....
                ....f1111f1111f11ff111f1111f....
                ....ff111f11f111111f11f111ff....
                ......f111f11ffffff11f111f......
                .......fffff1f1f1111fffff.......
                .......f11fff1f1111fff11f.......
                .......f1111ffffffff1111f.......
                .......f1f1111ffff1111f1f.......
                .......ff111fff11fff111ff.......
                .........fff..f11f..fff.........
                .............f111f..............
                .............f11f...............
                .............f11f...............
                .............f111f..............
                ..............f11f..............
                .............ff111ff............
                ............f1f111f1f...........
                ............f11fff11f...........
                .............f11111f............
                ..............fffff.............
                ................................
                ................................
                `,img`
                ................................
                ................................
                ................................
                ................................
                ................................
                ..........fffff..fffff..........
                .........f1ff11ff11ff1f.........
                ........f111ffffffff111f........
                ......ffffff11111111ffffff......
                .....f111ff111f111111ff111f.....
                ....f11fff1111f1111111fff11f....
                ....f1111f1111f11ff111f1111f....
                ....ff111f11f111111f11f111ff....
                ......f111f11ffffff11f111f......
                .......fffff1f1f1111fffff.......
                .......f11fff1f1111fff11f.......
                .......f1111ffffffff1111f.......
                .......f1f1111ffff1111f1f.......
                .......ff111fff11fff111ff.......
                .........fff..f11f..fff.........
                .............f111f..............
                .............f11f...............
                .............f11f...............
                .............f111f..............
                ..............f11f..............
                .............ff111ff............
                ............f1f111f1f...........
                ............f11fff11f...........
                .............f11111f............
                ..............fffff.............
                ................................
                ................................
                `,img`
                ................................
                ................................
                ................................
                ................................
                ................................
                ..........fffff..fffff..........
                .........f1ff11ff11ff1f.........
                ........f111ffffffff111f........
                ......ffffff11111111ffffff......
                .....f111ff111f11f111ff111f.....
                ....f11fff1111f11f1111fff11f....
                ....f1111f1111f11f1111f1111f....
                ....ff111f11f111111f11f111ff....
                ......f111f11ffffff11f111f......
                .......fffff1f1111f1fffff.......
                .......f11fff1ffff1fff11f.......
                .......f1111ffffffff1111f.......
                .......f1f1111ffff1111f1f.......
                .......ff111fff11fff111ff.......
                .........fff..f11f..fff.........
                .............f111f..............
                .............f11f...............
                .............f11f...............
                .............f111f..............
                ..............f11f..............
                .............ff111ff............
                ............f1f111f1f...........
                ............f11fff11f...........
                .............f11111f............
                ..............fffff.............
                ................................
                ................................
                `],
            50,
            false
            )
            projectile = sprites.createProjectileFromSprite(img`
                . 1 1 . 
                1 1 1 1 
                1 1 1 1 
                . 1 1 . 
                `, floweyNPC, 0, 0)
            projectile.x += -32
            projectile.y += -32
            projectile2 = sprites.createProjectileFromSprite(img`
                . 1 1 . 
                1 1 1 1 
                1 1 1 1 
                . 1 1 . 
                `, floweyNPC, 0, 0)
            projectile2.x += 32
            projectile2.y += -32
            for (let value5 of sprites.allOfKind(SpriteKind.Projectile)) {
                value5.setFlag(SpriteFlag.DestroyOnWall, false)
                value5.setFlag(SpriteFlag.GhostThroughWalls, true)
            }
            timer.after(500, function () {
                game.showLongText("Down here, LOVE is shared through...", DialogLayout.Bottom)
                game.showLongText("little white...", DialogLayout.Bottom)
                floweyBattleSpr.setImage(img`
                    ................................
                    ................................
                    ................................
                    ................................
                    ................................
                    ..........fffff..fffff..........
                    .........f1ff11ff11ff1f.........
                    ........f111ffffffff111f........
                    ......ffffff1f11f111ffffff......
                    .....f111ff1111f11f11ff111f.....
                    ....f11fff11111f11f111fff11f....
                    ....f1111f1111ff1ff111f1111f....
                    ....ff111f11f111111f11f111ff....
                    ......f111f11ffffff11f111f......
                    .......fffff1f1111f1fffff.......
                    .......f11fff1ffff1fff11f.......
                    .......f1111ffffffff1111f.......
                    .......f1f1111ffff1111f1f.......
                    .......ff111fff11fff111ff.......
                    .........fff..f11f..fff.........
                    .............f111f..............
                    .............f11f...............
                    .............f11f...............
                    .............f111f..............
                    ..............f11f..............
                    .............ff111ff............
                    ............f1f111f1f...........
                    ............f11fff11f...........
                    .............f11111f............
                    ..............fffff.............
                    ................................
                    ................................
                    `)
                game.showLongText("\"friendliness pellets.\" ", DialogLayout.Bottom)
                floweyBattleSpr.setImage(img`
                    ................................
                    ................................
                    ................................
                    ................................
                    ................................
                    ..........fffff..fffff..........
                    .........f1ff11ff11ff1f.........
                    ........f111ffffffff111f........
                    ......ffffff11111111ffffff......
                    .....f111ff111f11f111ff111f.....
                    ....f11fff1111f11f1111fff11f....
                    ....f1111f1111f11f1111f1111f....
                    ....ff111f11f111111f11f111ff....
                    ......f111f11ffffff11f111f......
                    .......fffff1f1111f1fffff.......
                    .......f11fff1ffff1fff11f.......
                    .......f1111ffffffff1111f.......
                    .......f1f1111ffff1111f1f.......
                    .......ff111fff11fff111ff.......
                    .........fff..f11f..fff.........
                    .............f111f..............
                    .............f11f...............
                    .............f11f...............
                    .............f111f..............
                    ..............f11f..............
                    .............ff111ff............
                    ............f1f111f1f...........
                    ............f11fff11f...........
                    .............f11111f............
                    ..............fffff.............
                    ................................
                    ................................
                    `)
                game.showLongText(" Are you ready? Move around! Get as many as you can!", DialogLayout.Bottom)
                timer.after(2000, function () {
                    projectile.follow(friskSoul, 32)
                    projectile2.follow(friskSoul, 32)
                })
            })
        })
    })
}
function animateCharacter () {
    characterAnimations.loopFrames(
    frisk,
    [img`
        . . . . . . . . . . . . . . . . 
        . . . . . f f f f f f . . . . . 
        . . . . f f f f f f f f . . . . 
        . . . . f f f f f f f f f . . . 
        . . . . . f 5 5 f f f f f . . . 
        . . . . . f f 5 5 5 f f f . . . 
        . . . . f 5 5 5 5 f f f f . . . 
        . . . . f f 5 5 f f f . . . . . 
        . . . . . f f f 5 f . . . . . . 
        . . . . . . . f f f f . . . . . 
        . . . . . . f 6 6 6 f . . . . . 
        . . . . . f a a f a f . . . . . 
        . . . . . f 6 f 5 f f . . . . . 
        . . . . . . f 6 f f . . . . . . 
        . . . . . . f f f f . . . . . . 
        . . . . . . . . . . . . . . . . 
        `],
    200,
    characterAnimations.rule(Predicate.NotMoving, Predicate.FacingLeft)
    )
    characterAnimations.loopFrames(
    frisk,
    [img`
        . . . . . f f f f f f . . . . . 
        . . . . f f f f f f f f . . . . 
        . . . . f f f f f f f f f . . . 
        . . . . . f 5 5 f f f f f . . . 
        . . . . . f f 5 5 5 f f f . . . 
        . . . . f 5 5 5 5 f f f f . . . 
        . . . . f f 5 5 f f f . . . . . 
        . . . . . f f f 5 f . . . . . . 
        . . . . . . . f f f f . . . . . 
        . . . . . . f 6 6 6 f . . . . . 
        . . . . . f a f a f f . . . . . 
        . . . . . f f 5 f 6 f . . . . . 
        . . . . f f f f 6 6 f . . . . . 
        . . . . f f f f f f f f . . . . 
        . . . . . . . . . f f . . . . . 
        . . . . . . . . . . . . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . f f f f f f . . . . . 
        . . . . f f f f f f f f . . . . 
        . . . . f f f f f f f f f . . . 
        . . . . . f 5 5 f f f f f . . . 
        . . . . . f f 5 5 5 f f f . . . 
        . . . . f 5 5 5 5 f f f f . . . 
        . . . . f f 5 5 f f f . . . . . 
        . . . . . f f f 5 f . . . . . . 
        . . . . . . . f f f f . . . . . 
        . . . . . . f 6 6 6 f . . . . . 
        . . . . . f a a f a f . . . . . 
        . . . . . f 6 f 5 f f . . . . . 
        . . . . . . f 6 f f . . . . . . 
        . . . . . . f f f f . . . . . . 
        . . . . . . . . . . . . . . . . 
        `,img`
        . . . . . f f f f f f . . . . . 
        . . . . f f f f f f f f . . . . 
        . . . . f f f f f f f f f . . . 
        . . . . . f 5 5 f f f f f . . . 
        . . . . . f f 5 5 5 f f f . . . 
        . . . . f 5 5 5 5 f f f f . . . 
        . . . . f f 5 5 f f f . . . . . 
        . . . . . f f f 5 f . . . . . . 
        . . . . . . . f f f f . . . . . 
        . . . . . . f 6 6 6 f . . . . . 
        . . . . . f a a a f f . . . . . 
        . . . . . f 6 6 f 5 f . . . . . 
        . . . . f f f 6 6 f f . . . . . 
        . . . . f f f f f f f f . . . . 
        . . . . . . . . . f f . . . . . 
        . . . . . . . . . . . . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . f f f f f f . . . . . 
        . . . . f f f f f f f f . . . . 
        . . . . f f f f f f f f f . . . 
        . . . . . f 5 5 f f f f f . . . 
        . . . . . f f 5 5 5 f f f . . . 
        . . . . f 5 5 5 5 f f f f . . . 
        . . . . f f 5 5 f f f . . . . . 
        . . . . . f f f 5 f . . . . . . 
        . . . . . . . f f f f . . . . . 
        . . . . . . f 6 6 6 f . . . . . 
        . . . . . f a a f a f . . . . . 
        . . . . . f 6 f 5 f f . . . . . 
        . . . . . . f 6 f f . . . . . . 
        . . . . . . f f f f . . . . . . 
        . . . . . . . . . . . . . . . . 
        `],
    200,
    characterAnimations.rule(Predicate.MovingLeft, Predicate.FacingLeft)
    )
    characterAnimations.loopFrames(
    frisk,
    [img`
        . . . . . . . . . . . . . . . . 
        . . . . . f f f f f f . . . . . 
        . . . . f f f f f f f f . . . . 
        . . . . f f f f 5 f f f . . . . 
        . . . f f 5 5 5 5 5 5 f f . . . 
        . . . f 5 f f 5 5 f f 5 f . . . 
        . . . f f 5 5 5 5 5 5 f f . . . 
        . . . f f f 5 f f 5 f f f . . . 
        . . . . . . f 5 5 f . . . . . . 
        . . . . . f f f f f f . . . . . 
        . . . . f f 6 6 6 6 f f . . . . 
        . . . f 6 f a a a a f 6 f . . . 
        . . . f 5 f 6 6 6 6 f 5 f . . . 
        . . . . f f f f f f f f . . . . 
        . . . . . f f f f f f . . . . . 
        . . . . . . . . . . . . . . . . 
        `],
    200,
    characterAnimations.rule(Predicate.NotMoving, Predicate.FacingDown)
    )
    characterAnimations.loopFrames(
    frisk,
    [img`
        . . . . . f f f f f f . . . . . 
        . . . . f f f f f f f f . . . . 
        . . . . f f f f 5 f f f . . . . 
        . . . f f 5 5 5 5 5 5 f f . . . 
        . . . f 5 f f 5 5 f f 5 f . . . 
        . . . f f 5 5 5 5 5 5 f f . . . 
        . . . f f f 5 f f 5 f f f . . . 
        . . . . . . f 5 5 f . . . . . . 
        . . . . . f f f f f f . . . . . 
        . . . . f f 6 6 6 6 f f . . . . 
        . . . f 5 5 f a a a f 6 f . . . 
        . . . f 5 5 f 6 6 f f f f . . . 
        . . . . f f f f f f f f . . . . 
        . . . . . f f f f f f f . . . . 
        . . . . . . f f . f f . . . . . 
        . . . . . . . . . . . . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . f f f f f f . . . . . 
        . . . . f f f f f f f f . . . . 
        . . . . f f f f 5 f f f . . . . 
        . . . f f 5 5 5 5 5 5 f f . . . 
        . . . f 5 f f 5 5 f f 5 f . . . 
        . . . f f 5 5 5 5 5 5 f f . . . 
        . . . f f f 5 f f 5 f f f . . . 
        . . . . . . f 5 5 f . . . . . . 
        . . . . . f f f f f f . . . . . 
        . . . . f f 6 6 6 6 f f . . . . 
        . . . f 6 f a a a a f 6 f . . . 
        . . . f 5 f 6 6 6 6 f 5 f . . . 
        . . . . f f f f f f f f . . . . 
        . . . . . f f f f f f . . . . . 
        . . . . . . . . . . . . . . . . 
        `,img`
        . . . . . f f f f f f . . . . . 
        . . . . f f f f f f f f . . . . 
        . . . . f f f f 5 f f f . . . . 
        . . . f f 5 5 5 5 5 5 f f . . . 
        . . . f 5 f f 5 5 f f 5 f . . . 
        . . . f f 5 5 5 5 5 5 f f . . . 
        . . . f f f 5 f f 5 f f f . . . 
        . . . . . . f 5 5 f . . . . . . 
        . . . . . f f f f f f . . . . . 
        . . . . f f 6 6 6 6 f f . . . . 
        . . . f 6 f a a a f 5 5 f . . . 
        . . . f f f f 6 6 f 5 5 f . . . 
        . . . . f f f f f f f f . . . . 
        . . . . f f f f f f f . . . . . 
        . . . . . f f . f f . . . . . . 
        . . . . . . . . . . . . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . f f f f f f . . . . . 
        . . . . f f f f f f f f . . . . 
        . . . . f f f f 5 f f f . . . . 
        . . . f f 5 5 5 5 5 5 f f . . . 
        . . . f 5 f f 5 5 f f 5 f . . . 
        . . . f f 5 5 5 5 5 5 f f . . . 
        . . . f f f 5 f f 5 f f f . . . 
        . . . . . . f 5 5 f . . . . . . 
        . . . . . f f f f f f . . . . . 
        . . . . f f 6 6 6 6 f f . . . . 
        . . . f 6 f a a a a f 6 f . . . 
        . . . f 5 f 6 6 6 6 f 5 f . . . 
        . . . . f f f f f f f f . . . . 
        . . . . . f f f f f f . . . . . 
        . . . . . . . . . . . . . . . . 
        `],
    200,
    characterAnimations.rule(Predicate.MovingDown, Predicate.FacingDown)
    )
    characterAnimations.loopFrames(
    frisk,
    [img`
        . . . . . . . . . . . . . . . . 
        . . . . . f f f f f f . . . . . 
        . . . . f f f f f f f f . . . . 
        . . . . f f f f f f f f . . . . 
        . . . f f f f f f f f f f . . . 
        . . . f f f f f f f f f f . . . 
        . . . f f f f f f f f f f . . . 
        . . . f f f f 5 5 f f f f . . . 
        . . . . f . f f f f . f . . . . 
        . . . . . f f f f f f . . . . . 
        . . . . f f 6 6 6 6 f f . . . . 
        . . . f 6 f a a a a f 6 f . . . 
        . . . f 5 f 6 6 6 6 f 5 f . . . 
        . . . . f f f f f f f f . . . . 
        . . . . . f f f f f f . . . . . 
        . . . . . . . . . . . . . . . . 
        `],
    200,
    characterAnimations.rule(Predicate.NotMoving, Predicate.FacingUp)
    )
    characterAnimations.loopFrames(
    frisk,
    [img`
        . . . . . f f f f f f . . . . . 
        . . . . f f f f f f f f . . . . 
        . . . . f f f f f f f f . . . . 
        . . . f f f f f f f f f f . . . 
        . . . f f f f f f f f f f . . . 
        . . . f f f f f f f f f f . . . 
        . . . f f f f 5 5 f f f f . . . 
        . . . . f . f f f f . f . . . . 
        . . . . . f f f f f f . . . . . 
        . . . . f f 6 6 6 6 f f . . . . 
        . . . f 6 f a a a a f 6 f . . . 
        . . . f 5 f 6 6 6 6 f 5 f . . . 
        . . . . f f f f f f f f f . . . 
        . . . . . f f f f f f f f . . . 
        . . . . . . f f . f f f . . . . 
        . . . . . . . . . . . . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . f f f f f f . . . . . 
        . . . . f f f f f f f f . . . . 
        . . . . f f f f f f f f . . . . 
        . . . f f f f f f f f f f . . . 
        . . . f f f f f f f f f f . . . 
        . . . f f f f f f f f f f . . . 
        . . . f f f f 5 5 f f f f . . . 
        . . . . f . f f f f . f . . . . 
        . . . . . f f f f f f . . . . . 
        . . . . f f 6 6 6 6 f f . . . . 
        . . . f 6 f a a a a f 6 f . . . 
        . . . f 5 f 6 6 6 6 f 5 f . . . 
        . . . . f f f f f f f f . . . . 
        . . . . . f f f f f f . . . . . 
        . . . . . . . . . . . . . . . . 
        `,img`
        . . . . . f f f f f f . . . . . 
        . . . . f f f f f f f f . . . . 
        . . . . f f f f f f f f . . . . 
        . . . f f f f f f f f f f . . . 
        . . . f f f f f f f f f f . . . 
        . . . f f f f f f f f f f . . . 
        . . . f f f f 5 5 f f f f . . . 
        . . . . f . f f f f . f . . . . 
        . . . . . f f f f f f . . . . . 
        . . . . f f 6 6 6 6 f f . . . . 
        . . . f 6 f a a a a f 6 f . . . 
        . . . f 5 f 6 6 6 6 f 5 f . . . 
        . . . f f f f f f f f f . . . . 
        . . . f f f f f f f f . . . . . 
        . . . . f f f . f f . . . . . . 
        . . . . . . . . . . . . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . f f f f f f . . . . . 
        . . . . f f f f f f f f . . . . 
        . . . . f f f f f f f f . . . . 
        . . . f f f f f f f f f f . . . 
        . . . f f f f f f f f f f . . . 
        . . . f f f f f f f f f f . . . 
        . . . f f f f 5 5 f f f f . . . 
        . . . . f . f f f f . f . . . . 
        . . . . . f f f f f f . . . . . 
        . . . . f f 6 6 6 6 f f . . . . 
        . . . f 6 f a a a a f 6 f . . . 
        . . . f 5 f 6 6 6 6 f 5 f . . . 
        . . . . f f f f f f f f . . . . 
        . . . . . f f f f f f . . . . . 
        . . . . . . . . . . . . . . . . 
        `],
    200,
    characterAnimations.rule(Predicate.MovingUp, Predicate.FacingUp)
    )
    characterAnimations.loopFrames(
    frisk,
    [img`
        . . . . . . . . . . . . . . . . 
        . . . . . f f f f f f . . . . . 
        . . . . f f f f f f f f . . . . 
        . . . f f f f f f f f f . . . . 
        . . . f f f f f 5 5 f . . . . . 
        . . . f f f 5 5 5 f f . . . . . 
        . . . f f f f 5 5 5 5 f . . . . 
        . . . . . f f f 5 5 f f . . . . 
        . . . . . . f 5 f f f . . . . . 
        . . . . . f f f f . . . . . . . 
        . . . . . f 6 6 6 f . . . . . . 
        . . . . . f a f a a f . . . . . 
        . . . . . f f 5 f 6 f . . . . . 
        . . . . . . f f 6 f . . . . . . 
        . . . . . . f f f f . . . . . . 
        . . . . . . . . . . . . . . . . 
        `],
    200,
    characterAnimations.rule(Predicate.NotMoving, Predicate.FacingRight)
    )
    characterAnimations.loopFrames(
    frisk,
    [img`
        . . . . . f f f f f f . . . . . 
        . . . . f f f f f f f f . . . . 
        . . . f f f f f f f f f . . . . 
        . . . f f f f f 5 5 f . . . . . 
        . . . f f f 5 5 5 f f . . . . . 
        . . . f f f f 5 5 5 5 f . . . . 
        . . . . . f f f 5 5 f f . . . . 
        . . . . . . f 5 f f f . . . . . 
        . . . . . f f f f . . . . . . . 
        . . . . . f 6 6 6 f . . . . . . 
        . . . . . f f a f a f . . . . . 
        . . . . . f 6 f 5 f f . . . . . 
        . . . . . f 6 6 f f f f . . . . 
        . . . . f f f f f f f f . . . . 
        . . . . . f f . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . f f f f f f . . . . . 
        . . . . f f f f f f f f . . . . 
        . . . f f f f f f f f f . . . . 
        . . . f f f f f 5 5 f . . . . . 
        . . . f f f 5 5 5 f f . . . . . 
        . . . f f f f 5 5 5 5 f . . . . 
        . . . . . f f f 5 5 f f . . . . 
        . . . . . . f 5 f f f . . . . . 
        . . . . . f f f f . . . . . . . 
        . . . . . f 6 6 6 f . . . . . . 
        . . . . . f a f a a f . . . . . 
        . . . . . f f 5 f 6 f . . . . . 
        . . . . . . f f 6 f . . . . . . 
        . . . . . . f f f f . . . . . . 
        . . . . . . . . . . . . . . . . 
        `,img`
        . . . . . f f f f f f . . . . . 
        . . . . f f f f f f f f . . . . 
        . . . f f f f f f f f f . . . . 
        . . . f f f f f 5 5 f . . . . . 
        . . . f f f 5 5 5 f f . . . . . 
        . . . f f f f 5 5 5 5 f . . . . 
        . . . . . f f f 5 5 f f . . . . 
        . . . . . . f 5 f f f . . . . . 
        . . . . . f f f f . . . . . . . 
        . . . . . f 6 6 6 f . . . . . . 
        . . . . . f f a a a f . . . . . 
        . . . . . f 5 f 6 6 f . . . . . 
        . . . . . f f 6 6 f f f . . . . 
        . . . . f f f f f f f f . . . . 
        . . . . . f f . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . f f f f f f . . . . . 
        . . . . f f f f f f f f . . . . 
        . . . f f f f f f f f f . . . . 
        . . . f f f f f 5 5 f . . . . . 
        . . . f f f 5 5 5 f f . . . . . 
        . . . f f f f 5 5 5 5 f . . . . 
        . . . . . f f f 5 5 f f . . . . 
        . . . . . . f 5 f f f . . . . . 
        . . . . . f f f f . . . . . . . 
        . . . . . f 6 6 6 f . . . . . . 
        . . . . . f a f a a f . . . . . 
        . . . . . f f 5 f 6 f . . . . . 
        . . . . . . f f 6 f . . . . . . 
        . . . . . . f f f f . . . . . . 
        . . . . . . . . . . . . . . . . 
        `],
    200,
    characterAnimations.rule(Predicate.MovingRight, Predicate.FacingRight)
    )
}
sprites.onOverlap(SpriteKind.FinalProjectile, SpriteKind.Soul, function (sprite, otherSprite) {
    sprites.destroyAllSpritesOfKind(SpriteKind.FinalProjectile)
    statusbar.value += 19
    animation.runImageAnimation(
    floweyBattleSpr,
    [img`
        ..........fffff..fffff..........
        .........f1ff11ff11ff1f.........
        ........f111ffffffff111f........
        ......ffffff11111111ffffff......
        .....f111ff1ff1111ff1ff111f.....
        ....f11fff11f1f11f1f11fff11f....
        ....f1111f11fff11fff11f1111f....
        ....ff111f1f11111111f1f111ff....
        ......f111f1ffffffff1f111f......
        .......ffff1f1f11f1f1ffff.......
        ..........f1ffffffff1f..........
        ..........f1ffffffff1f..........
        ..........f1f1f11f1f1f..........
        .......fffff1ffffff1fffff.......
        .......f11fff111111fff11f.......
        .......f1111ffffffff1111f.......
        .......f1f1111ffff1111f1f.......
        .......ff111fff11fff111ff.......
        .........fff..f11f..fff.........
        .............f111f..............
        .............f111f..............
        .............f11f...............
        .............f11f...............
        .............f111f..............
        ..............f11f..............
        .............ff111ff............
        ............f1f111f1f...........
        ............f11fff11f...........
        .............f11111f............
        ..............fffff.............
        ................................
        ................................
        `,img`
        ................................
        ..........fffff..fffff..........
        .........f1ff11ff11ff1f.........
        ........f111ffffffff111f........
        ......ffffff11111111ffffff......
        .....f111ff1ff1111ff1ff111f.....
        ....f11fff11f1f11f1f11fff11f....
        ....f1111f11fff11fff11f1111f....
        ....ff111f1f11111111f1f111ff....
        ......f111f1ff1111ff1f111f......
        .......ffff1f1ffff1f1ffff.......
        ..........f1fff11fff1f..........
        ..........f1f1ffff1f1f..........
        ..........f11ff11ff11f..........
        .......fffff11ffff11fffff.......
        .......f11fff111111fff11f.......
        .......f1111ffffffff1111f.......
        .......f1f1111ffff1111f1f.......
        .......ff111fff11fff111ff.......
        .........fff..f11f..fff.........
        .............f111f..............
        .............f11f...............
        .............f11f...............
        .............f111f..............
        ..............f11f..............
        .............ff111ff............
        ............f1f111f1f...........
        ............f11fff11f...........
        .............f11111f............
        ..............fffff.............
        ................................
        ................................
        `],
    100,
    false
    )
    timer.after(500, function () {
        floweyBattleSpr.setImage(img`
            ................................
            ................................
            ................................
            ................................
            ................................
            ..........fffff..fffff..........
            .........f1ff11ff11ff1f.........
            ........f111ffffffff111f........
            ......ffffff11111111ffffff......
            .....f111ff11f1111f11ff111f.....
            ....f11fff1111f11f1111fff11f....
            ....f1111f1111f11f1111f1111f....
            ....ff111f111111111111f111ff....
            ......f111f111ffff111f111f......
            .......fffff1f1111f1fffff.......
            .......f11fff1ffff1fff11f.......
            .......f1111ffffffff1111f.......
            .......f1f1111ffff1111f1f.......
            .......ff111fff11fff111ff.......
            .........fff..f11f..fff.........
            .............f111f..............
            .............f11f...............
            .............f11f...............
            .............f111f..............
            ..............f11f..............
            .............ff111ff............
            ............f1f111f1f...........
            ............f11fff11f...........
            .............f11111f............
            ..............fffff.............
            ................................
            ................................
            `)
        timer.after(1000, function () {
            floweyBattleSpr.setImage(img`
                ................................
                ................................
                ................................
                ................................
                ................................
                ..........fffff..fffff..........
                .........f1ff11ff11ff1f.........
                ........f111ffffffff111f........
                ......ffffff11111111ffffff......
                .....f111ff1111f11f11ff111f.....
                ....f11fff11111f11f111fff11f....
                ....f1111f11111f11f111f1111f....
                ....ff111f111111111111f111ff....
                ......f111f111ffff111f111f......
                .......fffff1f1111f1fffff.......
                .......f11fff1ffff1fff11f.......
                .......f1111ffffffff1111f.......
                .......f1f1111ffff1111f1f.......
                .......ff111fff11fff111ff.......
                .........fff..f11f..fff.........
                .............f111f..............
                .............f11f...............
                .............f11f...............
                .............f111f..............
                ..............f11f..............
                .............ff111ff............
                ............f1f111f1f...........
                ............f11fff11f...........
                .............f11111f............
                ..............fffff.............
                ................................
                ................................
                `)
            timer.after(1000, function () {
                floweyBattleSpr.setImage(img`
                    ................................
                    ................................
                    ................................
                    ................................
                    ................................
                    ..........fffff..fffff..........
                    .........f1ff11ff11ff1f.........
                    ........f111ffffffff111f........
                    ......ffffff11111111ffffff......
                    .....f111ff1111f11f11ff111f.....
                    ....f11fff11111f11f111fff11f....
                    ....f1111f11111f11f111f1111f....
                    ....ff111f111111111111f111ff....
                    ......f111f111ffff111f111f......
                    .......fffff1f1111f1fffff.......
                    .......f11fff1ffff1fff11f.......
                    .......f1111ffffffff1111f.......
                    .......f1f1111ffff1111f1f.......
                    .......ff111fff11fff111ff.......
                    .........fff..f11f..fff.........
                    .............f111f..............
                    .............f11f...............
                    .............f11f...............
                    .............f111f..............
                    ..............f11f..............
                    .............ff111ff............
                    ............f1f111f1f...........
                    ............f11fff11f...........
                    .............f11111f............
                    ..............fffff.............
                    ................................
                    ................................
                    `)
                projectile3 = sprites.createProjectileFromSide(img`
                    . . . . . . . . . . . . . . . . 
                    . . . . . . f f f . . . . . . . 
                    . . . . . . f 1 f . . . . . . . 
                    . . . . . f f 1 1 f . . . . . . 
                    . . . . . f f 1 1 f f . . . . . 
                    . . . . f 1 f 1 1 f 1 f . . . . 
                    . . . . f 1 f 1 1 1 1 f . . . . 
                    . . . . f 1 1 1 1 1 1 f . . . . 
                    . . . . f 1 1 1 1 1 1 f . . . . 
                    . . . . f 1 1 1 1 1 1 1 f . . . 
                    . . . f 1 1 1 f f 1 1 1 f . . . 
                    . . . f 1 1 f 1 1 f 1 1 f . . . 
                    . . . f 1 1 f 1 1 f 1 1 f . . . 
                    . . . f 1 1 1 f f 1 1 1 f . . . 
                    . . . . f 1 1 1 1 1 1 f . . . . 
                    . . . . . f f f f f f . . . . . 
                    `, -80, 0)
                projectile3.y = 32
            })
        })
    })
})
function createPLayer () {
    frisk = sprites.create(img`
        . . . . . . . . . . . . . . . . 
        . . . . . f f f f f f . . . . . 
        . . . . f f f f f f f f . . . . 
        . . . . f f f f 5 f f f . . . . 
        . . . f f 5 5 5 5 5 5 f f . . . 
        . . . f 5 f f 5 5 f f 5 f . . . 
        . . . f f 5 5 5 5 5 5 f f . . . 
        . . . f f f 5 f f 5 f f f . . . 
        . . . . . . f 5 5 f . . . . . . 
        . . . . . f f f f f f . . . . . 
        . . . . f f 6 6 6 6 f f . . . . 
        . . . f 6 f a a a a f 6 f . . . 
        . . . f 5 f 6 6 6 6 f 5 f . . . 
        . . . . f f f f f f f f . . . . 
        . . . . . f f f f f f . . . . . 
        . . . . . . . . . . . . . . . . 
        `, SpriteKind.Player)
    friskHitbox = sprites.create(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . 6 6 6 6 6 6 . . . . . 
        . . . . . 6 6 6 6 6 6 . . . . . 
        . . . . . 1 1 6 6 1 1 . . . . . 
        . . . . . 6 6 6 6 6 6 . . . . . 
        . . . . . 6 6 6 6 6 6 . . . . . 
        . . . . . 6 1 1 1 1 6 . . . . . 
        . . . . . 6 6 6 6 6 6 . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, SpriteKind.Hitbox)
    controller.moveSprite(friskHitbox, 50, 50)
    frisk.z = 2
    frisk.setFlag(SpriteFlag.Ghost, true)
    friskHitbox.setFlag(SpriteFlag.Invisible, true)
    scene.cameraFollowSprite(friskHitbox)
    animateCharacter()
}
sprites.onOverlap(SpriteKind.Projectile, SpriteKind.BattleSpr, function (sprite, otherSprite) {
    sprites.destroyAllSpritesOfKind(SpriteKind.Projectile)
    floweyBattleSpr.setImage(img`
        ................................
        ................................
        ................................
        ................................
        ................................
        ..........fffff..fffff..........
        .........f1ff11ff11ff1f.........
        ........f111ffffffff111f........
        ......fffffff111111fffffff......
        .....f111fff1f1111f1fff111f.....
        ....f11ffff11f1111f11ffff11f....
        ....f1111f1ff11ff11ff1f1111f....
        ....ff111f1111f11f1111f111ff....
        ......f111f111ffff111f111f......
        .......fffff11ffff11fffff.......
        .......f11ffffffffffff11f.......
        .......f1111ffffffff1111f.......
        .......f1f1111ffff1111f1f.......
        .......ff111fff11fff111ff.......
        .........fff..f11f..fff.........
        .............f111f..............
        .............f11f...............
        .............f11f...............
        .............f111f..............
        ..............f11f..............
        .............ff111ff............
        ............f1f111f1f...........
        ............f11fff11f...........
        .............f11111f............
        ..............fffff.............
        ................................
        ................................
        `)
    floweyBattleSpr.setFlag(SpriteFlag.Ghost, true)
    floweyBattleSpr.vx = -160
    timer.after(2500, function () {
        sprites.destroyAllSpritesOfKind(SpriteKind.Soul)
        sprites.destroyAllSpritesOfKind(SpriteKind.StatusBar)
        sprites.destroyAllSpritesOfKind(SpriteKind.Flowey)
        sprites.destroyAllSpritesOfKind(SpriteKind.BattleSpr)
        createPLayer()
        room += 1
        loadNextRoom()
    })
})
let projectile3: Sprite = null
let frisk: Sprite = null
let sansNPC: Sprite = null
let friskSoul: Sprite = null
let projectile2: Sprite = null
let floweyNPC: Sprite = null
let projectile: Sprite = null
let statusbar: StatusBarSprite = null
let floweyBattleSpr: Sprite = null
let friskHitbox: Sprite = null
let friskActHitbox: Sprite = null
let dialogueOpen = false
let room = 0
room = 0
createPLayer()
loadNextRoom()
game.onUpdate(function () {
    for (let value6 of sprites.allOfKind(SpriteKind.Player)) {
        value6.setPosition(friskHitbox.x, friskHitbox.y)
    }
})
